// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJzMlk1yozAQRvecost7X4DF7OYcqrZoTBeNpNLP2MzpU4CTIjY4zkKJeimh77UeIDhCT2MNA3nsuQKIHIVqOCwDhwrAkxAGquFEESuAhoL27CJbU8OfCgBuq2GwTRKqAFomaUI9zx3B4EArwlRxdFTD2dvkbiMbqZ9z1lnolMeGrUqRhf/jtOrjoq30qe738V6b5KW+4Ny3t26Rrji4Wca6ls56Gi/WN3dzT/qY6u8SuEAfjGgSSYJenTHSBUfVEUrslCPfWj+g0ZRD0PewBflqMHQni75R6DiHmT1ASQ7oH2tS2iYTQxYHO4DyHNwe2xAxppwq9jgFGWnZ0wVFVIcZfTyllGhDbAhKMJLRY1YhO6ASnaxOeRW09Vk+MS/RSrQTkzEked+eR0aJJpITNv1PnCZ7pIKssInkW9SUxcRmekG7F9ZkAim6Ovbz//R8s7KcHC+wftHMWwAAAP//VoWH7A=="
}
