// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJzMkk1ugzAQhfecYpR9LuBFdz0HmuDXxsLYlseQcvuKn1aUQNQNid/SI943/vCZavSKGkSuTUGUTLJQdJoOTgVRhAULFF2QuCDSkCqakIx3it4KIpq/psbr1qIg+jCwWtQ4O5PjBgvCkNQHKPqMvg3zyUbr355ll2a5XjxHXXIwv9Ot2iHrC/xkEzmPdgDrhZZL4YubMF5/mWmlGv3NR72aPVhgyPtUOEHvHaAzFcrKty7JIQ52APk5kMSpPdLBHSA/B22wxtVSWi9SstOl5QRX9Qda+QcyX0++Q+wMbk/ws4HK18v01MffeeUnyNnjZWTImgpOcOybeQR5oYvvAAAA///zBSMR"
}
