// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJzMkEFugzAQRfecYpR9LuBFdz2HNcG/7QhjWx5Dyu0rAq0oIVE3qPylR/5v5p2pwWCoReZGKqIixcPQaXo4VUQZHqwwdEHhishB6yypSAyGXioimn9TG13nURG9CbxTc5udKXCLBWFMGRIMvefYpfllo/V3z7LLsX5cImdnOcnPdKt2zPqA72wi59EDwHqh5VL45Dbdzl9mWqnBcI3ZrWZPFhjzOhVO0HsH6KWGrWMXiu7i4AHgeA60cOn2dHAHOJ6DLnkJjVofVS0HZz0XhHrY0cofkAfy5KVGUKiNPXIvuO5h5hnkH118BQAA//9PMIsU"
}
