- module: emcunity
  metricsets: ["health"]
  enabled: false 
  period: 120s
  hosts: ["https://emc_unity_hostA","https://emc_unity_hostb"]
  username: "${EMC_UNITY_USER}"
  password: "${EMC_UNITY_PWD}"
  debug: true
  # EMC Unity - Specifies the number of resource type instances that form a page.
  per_page: 2000


