// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package danslaptop

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "danslaptop", asset.ModuleFieldsPri, AssetDanslaptop); err != nil {
		panic(err)
	}
}

// AssetDanslaptop returns asset data.
// This is the base64 encoded zlib format compressed contents of module/danslaptop.
func AssetDanslaptop() string {
	return "eJx8jkEOwiAURPecYtJ9L8DCnQdBGQ0pFAK/0d7e1FptCXGWM8l702PgrGHNWLxJEpMCxImnRvcrOwVkeppCjQvFKMCyXLNL4uKocVIAdhSEaCdPBdwcvS36vfcYTWBlWyJzosY9x2lrGvQja88TF/gtW7Ql9f8tTdMHdOTW+v0FPk1InodtezJwfsRsq+2Pd8l5Ba5S9QoAAP//9a9yLQ=="
}
