- module: horizon
  metricsets: ["health"]
  enabled: false 
  period: 120s
  host: "localhost"
  protocol: "https"
  port: 443
  username: ${HORIZON_USERNAME}
  password: ${HORIZON_PASSWORD}
  domain: ${HORIZON_DOMAIN}

