// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package cisco_intersight

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "cisco_intersight", asset.ModuleFieldsPri, AssetCiscoIntersight); err != nil {
		panic(err)
	}
}

// AssetCiscoIntersight returns asset data.
// This is the base64 encoded zlib format compressed contents of module/cisco_intersight.
func AssetCiscoIntersight() string {
	return "eJx8j8FuhSAQRfd8xY17f4BFd/2OhsqtElEIjGn9+0ZpX3xI3lnOTM6902PmrjG4PIQPtwpTduMkChAnnhpdveoUkOhpMjU+KUYBlnlILooLq8abAnAzYgl281TAl6O3WZ9XPVazsJl/IHukxpjCFv8mjaRn49U60XiZHuOW76D+5p9mVuFmritca/DHLPF8/UrpMnP/DslWuxfJB+9FWELVbwAAAP//tAF9pw=="
}
