// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJzMlstu8yAQhfd+ilH2eQEv/t3/HGgKxwkyBsSlifv0lS+t3NRp0gUqZwnhnJmPCfKReowtDQjc64Yo6WTQ0mFZODREAQYc0dILEjdEClEG7ZN2tqV/DRGtp2lwKhs0RJ2GUbGd945kecAmYVIaPVo6BZf9urLj+tVn68VeBFbaiZy00W88nfr80Z77pNs+PrSbvOhBzm152xJx5cHPMLZaKusxXlxQN3s/1DHp/2K4hH4jImFMNhzEiRMuPIoz2KSz8AidCwNbiRKAfhdbES+FVy0hpMs2xRJk7gXUx2C9spg45ZIo7uVURKS7bCdXROlCkb/Ng5y6iKRsLUyRydh1r6v77I22/Tq1gq0SxsUoDCdYORaC8nRoRazOXPAJ2TOvqHdtE0LHEkWa33WvqHujJWyEwNXrMH8jzZdV5OV8IusPybwHAAD//zMs9h8="
}
